import Generator, { Context, File, Template } from '../Generator.js';
import Pretty from '../Pretty.js';
import { SWIFT_LANG_CODE } from './const.js';

export const entityTemplate = (context: Context): File => {
  const content = context
    .content('file-header')
    .content('open')
    .contentEach({ directive: 'field' }, 'property')
    .content('init')
    .content('close')
    .body;
  return new File(`${context.get('name')}.swift`, content);
}

export const entityFileHeader = (context: Context): string => {
  return `
///
/// ${context.get('name')}.swift
///
/// Auto Generated by soil-schema
///
`;
}

export const entityOpen = (context: Context): string => {
  return `
/// ${context.get('name')}
struct ${context.get('name')}: Codable {
`;
}

export const entityInit = (context: Context): string => {
  return context
    .dup()
    .string(`init(${context.renderEach({ directive: 'field', separator: ', ' }, 'signature')}) {`)
    .contentEach({ directive: 'field' }, 'assign-property')
    .string('}')
    .body;
}

export const pretty = (content: string, context: Context): string => {
  return new Pretty(content).pretty({
    indentBlock: ['{}', '()'],
    comment: ['//', '///'],
    stripComment: context.hasAttribute('strip-comment'),
    indent: '    ',
  });
}

export default (generator: Generator) => {
  generator
    .template(new Template(SWIFT_LANG_CODE, 'entity', entityTemplate))
    .renderer(SWIFT_LANG_CODE, 'entity', 'file-header', entityFileHeader)
    .renderer(SWIFT_LANG_CODE, 'entity', 'open', entityOpen)
    .renderer(SWIFT_LANG_CODE, 'entity', 'init', entityInit)
    .renderer(SWIFT_LANG_CODE, 'entity', 'close', () => '}')

    .hookContent('swift:entity:template', pretty);
}